---
title: "Project tests"
author: "Piping Hot"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
```



```{proposal-stuff}
stroke_risk %>%
  filter(smoking_status != "Unknown") %>%
  count(smoking_status, stroke) %>%
  ggplot(aes(x = stroke, y = n, fill = smoking_status)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  labs(x = "Stroke", y = "Proportion", fill = "Smoking status") +
  theme_minimal()
```

```{propsal-stuff2}
stroke_risk %>%
  count(gender, stroke) %>%
  filter(gender != "Other")
```

```{r makeup-artist, warning = FALSE}
stroke_risk <- read.csv(here::here("data/healthcare-dataset-stroke-data.csv"))
stroke_risk <- stroke_risk %>%
  mutate(
    #hypertension = if_else(hypertension == 1, TRUE, FALSE),
    #heart_disease = if_else(heart_disease == 1, TRUE, FALSE),
    #stroke = if_else(stroke == 1, TRUE, FALSE),
    bmi = if_else(bmi == "N/A", NA_real_, as.numeric(bmi))
  )
glimpse(stroke_risk)

stroke_risk %>%
  mutate(stroke = if_else(stroke == 1, "Yes", "No"), stroke = fct_rev(stroke)) %>%
  ggplot(aes(x = avg_glucose_level, fill = stroke)) +
  geom_density(alpha = 0.5) +
  labs(
    x = "Average Glucose Level",
    y = "Density",
    title = "Average glucose level compared to stroke risk",
    fill = "Stroke"
  ) +
  scale_fill_viridis_d() +
  theme_minimal()

```

```{r photographer}
 median_age_stroke <- stroke_risk %>%
  mutate( stroke = if_else(stroke == "1", "Yes", "No")) %>%
  group_by(stroke) %>%
  summarise(median_age = median(age))

median_age_stroke %>%
  ggplot(aes(stroke, median_age, fill = stroke)) +
  geom_col() +
  scale_fill_manual(values = c("Purple", "Orange")) +
  labs(x = "Stroke", y = "Midean Age", title = "The Avrage Age of Patients who have had a Stroke") +
  theme(legend.position="none") +
  theme_minimal() 
  
  
  
```

```{r the modelling man}
stroke_risk <- read.csv(here::here("data/healthcare-dataset-stroke-data.csv"))
stroke_risk_cleaned <- stroke_risk %>%
  filter(gender != "Other") %>%
  mutate(
    #hypertension = if_else(hypertension == 1, TRUE, FALSE),
    #heart_disease = if_else(heart_disease == 1, TRUE, FALSE),
    #stroke = if_else(stroke == 1, TRUE, FALSE),
    bmi = if_else(bmi == "N/A", NA_real_, as.numeric(bmi))
  )

stroke_risk_cleaned %>%
  group_by(gender) %>%
  count()


logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- (odds / (1 + odds)) * 100
  return(prob)
}


stroke_fit <- logistic_reg() %>%
  set_engine("glm") %>%
  fit(factor(avg_glucose_level) ~  bmi, data = stroke_risk_cleaned, family = "binomial")
glance(stroke_fit)

tidy(stroke_fit)
estimates <- tidy(stroke_fit) %>%
  pull(estimate)

logit2prob(estimates[1])

 stroke_risk_cleaned %>%
  ggplot(aes(x = bmi, y = avg_glucose_level)) +
  geom_smooth(method = "lm")
  

```